application: schedule-pro
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /css
  static_dir: static/css

- url: /scripts
  static_dir: static/scripts
  
- url: /images
  static_dir: static/images
  
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /
  script: main.py

- url: /.*
  script: main.py
  login: required

builtins:
- datastore_admin: on
